apiVersion: v2
appVersion: "1.25.0"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.0.8
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.truecharts.org/
  version: 8.0.1
deprecated: false
description: Unofficial Bitwarden compatible server written in Rust
home: https://github.com/truecharts/apps/tree/master/charts/stable/vaultwarden
icon: https://truecharts.org/_static/img/appicons/vaultwarden.png
keywords:
- bitwarden
- bitwardenrs
- bitwarden_rs
- vaultwarden
- password
- rust
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: vaultwarden
sources:
- https://github.com/dani-garcia/vaultwarden
type: application
version: 16.0.0
annotations:
  truecharts.org/catagories: |
    - security
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
