apiVersion: v2
appVersion: "1.27.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://deps.truecharts.org/
    version: 11.0.22
deprecated: false
description: Unofficial Bitwarden compatible server written in Rust
home: https://truecharts.org/charts/stable/vaultwarden
icon: https://truecharts.org/img/hotlink-ok/chart-icons/vaultwarden.png
keywords:
  - bitwarden
  - bitwardenrs
  - bitwarden_rs
  - vaultwarden
  - password
  - rust
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: vaultwarden
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/vaultwarden
  - https://hub.docker.com/r/vaultwarden/server
  - https://github.com/dani-garcia/vaultwarden
type: application
version: 19.0.21
annotations:
  truecharts.org/catagories: |
    - security
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
