apiVersion: v2
appVersion: "1.24.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 9.1.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 7.0.2
deprecated: false
description: Unofficial Bitwarden compatible server written in Rust
home: https://github.com/truecharts/apps/tree/master/charts/stable/vaultwarden
icon: https://truecharts.org/_static/img/appicons/vaultwarden.png
keywords:
- bitwarden
- bitwardenrs
- bitwarden_rs
- vaultwarden
- password
- rust
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: vaultwarden
sources:
- https://github.com/dani-garcia/vaultwarden
type: application
version: 14.0.2
annotations:
  truecharts.org/catagories: |
    - security
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
