apiVersion: v2
appVersion: "1.25.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.6.11
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 8.0.95
deprecated: false
description: Unofficial Bitwarden compatible server written in Rust
home: https://truecharts.org/docs/charts/stable/vaultwarden
icon: https://truecharts.org/img/hotlink-ok/chart-icons/vaultwarden.png
keywords:
  - bitwarden
  - bitwardenrs
  - bitwarden_rs
  - vaultwarden
  - password
  - rust
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: vaultwarden
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/vaultwarden
  - https://github.com/dani-garcia/vaultwarden
type: application
version: 16.0.44
annotations:
  truecharts.org/catagories: |
    - security
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
